### ISSUE TITLE
I can't describe types of url params on Lumen 8.x

### ISSUE THREAD

**Issue by Talented-Business** [knuckleswtf/scribe#110]
Following is a description of an action
    /**
     * upload image of the list.
     *
     * @authenticated
     * @urlParam username required the username of user
     * @urlParam id required The ID of the list
     * @bodyParam image file required
     * @response ok
     */
$router->post('users/{username}/lists/{id}/image', 'ListController@uploadImage');
In there, username is string, id is integer.
![api doc integer issue](https://user-images.githubusercontent.com/2536597/95407178-45a24800-0957-11eb-814d-62dec1a27bce.png)
can I describe the type as integer?

**Comment by shalvah** [comment]
Types of URL params are not supported in v1. They're supported in v2, but I just need to make time to release it. You can use it by changing your composer requirement to dev-v2. https://scribe.readthedocs.io/en/v2/migrating-v2.html

**Comment by Talented-Business** [comment]
I installed v2.x-dev and copied config.php and  runned "php artisan scribe:generate"
But it doesn't work.
![api doc integer issue](https://user-images.githubusercontent.com/2536597/95513926-10990280-09f6-11eb-829b-9e43494348fa.png)

**Comment by shalvah** [comment]
Hmm. Have you tried with verbose?

**Comment by Talented-Business** [comment]
No
What is verbose?
How can I use it?

**Comment by shalvah** [comment]
Check the troubleshooting guide in the docs.

**Comment by Talented-Business** [comment]
![api doc integer issue](https://user-images.githubusercontent.com/2536597/95688995-edb25c80-0c48-11eb-9839-bf539da80ad1.png)

**Comment by shalvah** [comment]
That looks like a case of a missing alias. Try adding an alias for the `Str` class and let me know if it works. See [this article](https://medium.com/@basantbesra/create-aliases-for-your-classes-in-laravel-6814c349d3af).

I think the full class name is Illuminate\Support\Str, so the alias line would be

```
'Str' => \Illuminate\Support\Str::class
```

**Comment by shalvah** [comment]
Or [this SO answer](https://stackoverflow.com/a/59503877/7370522). Let me know if that fixes it, because the package shouldn't need you to do that.

**Comment by Talented-Business** [comment]
it is not Laravel, it is lumen.
I added config/app.php, but it doesn't work.

**Comment by Talented-Business** [comment]
I added following section in the bootstrap/app.php
if (!class_exists('Str')) {
    class_alias('Illuminate\Support\Str::class', 'Str');
}
But it shows following error.
In app.php line 30:

  Class 'Illuminate\Support\Str::class' not found

**Comment by shalvah** [comment]
You made a mistake. It should be:

```php
class_alias(Illuminate\Support\Str::class, 'Str');
```

(No quotes around the class name.)

**Comment by Talented-Business** [comment]
yes it is working
In Lumen, it requires "composer require illuminate/support"

**Comment by shalvah** [comment]
Alright, thanks for the feedback. Didn't know illuminate/support wasn't included in Lumen (or is it your installation)? I'll find a way around that, anyway.

Just to confirm, were you finally able to add types for the URL parameters?

**Comment by shalvah** [comment]
Just pushed an update that should fix the alias issue. You can run `composer update knuckleswtf/scribe` and remove the custom changes you had to add.

BTW, illuminate/support has always been listed as a part of our dependencies, so I'm not sure why you had to require it again separately.

**Comment by Talented-Business** [comment]
![api doc integer issue](https://user-images.githubusercontent.com/2536597/95801840-a0141d80-0d36-11eb-9ef5-84ce611ca6d4.png)

**Comment by shalvah** [comment]
Are you using a custom strategy or something?

**Comment by Talented-Business** [comment]
No
I returned 1.9.
it is working.
And then I updated to 2.0.
And I copy new config/scribe.php and updated.
But it doesn't work
![api doc integer issue](https://user-images.githubusercontent.com/2536597/96177269-8bb76700-0f68-11eb-8e4b-36c4ab52a4ec.png)
What is wrong?

**Comment by shalvah** [comment]
@Talented-Business please try again. I pushed out an update to v2.

**Comment by Talented-Business** [comment]
I updated 
But it still shows error.
In 9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php line 8:
                                                                                                                                                                                                    
  [ErrorException]                                                                                                                                                                                  
  Undefined index: name (View: F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\resources\views\partials\body-parameters.blade.php) (View: F:\webapp\www\laravel\bigtaby\lumen\vendo   
  r\knuckleswtf\scribe\resources\views\partials\body-parameters.blade.php) (View: F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\resources\views\partials\body-parameters.blade.ph   
  p)                                                                                                                                                                                                
                                                                                                                                                                                                    

Exception trace:
  at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php:8
 Illuminate\View\Engines\CompilerEngine->handleViewException() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:60
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:169
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:172
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:173
 Knuckles\Scribe\Writing\Writer->generateMarkdownOutputForEachRoute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:394
 Knuckles\Scribe\Writing\Writer->writeEndpointsMarkdownFile() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:136
 Knuckles\Scribe\Writing\Writer->writeMarkdownAndSourceFiles() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:104
 Knuckles\Scribe\Writing\Writer->writeDocs() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Commands\GenerateDocumentation.php:83
 Knuckles\Scribe\Commands\GenerateDocumentation->handle() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Container.php:596
 Illuminate\Container\Container->call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:136
 Illuminate\Console\Command->execute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Command\Command.php:258
 Symfony\Component\Console\Command\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:121
 Illuminate\Console\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:920
 Symfony\Component\Console\Application->doRunCommand() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:266
 Symfony\Component\Console\Application->doRun() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:142
 Symfony\Component\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Application.php:93
 Illuminate\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\laravel\lumen-framework\src\Console\Kernel.php:116
 Laravel\Lumen\Console\Kernel->handle() at F:\webapp\www\laravel\bigtaby\lumen\artisan:35

In 9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php line 8:
                                                                                                                                                                                                    
  [ErrorException]
  Undefined index: name (View: F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\resources\views\partials\body-parameters.blade.php) (View: F:\webapp\www\laravel\bigtaby\lumen\vendo   
  r\knuckleswtf\scribe\resources\views\partials\body-parameters.blade.php)                                                                                                                          
                                                                                                                                                                                                    

Exception trace:
  at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php:8
 Illuminate\View\Engines\CompilerEngine->handleViewException() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:60
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Concerns\ManagesComponents.php:96
 Illuminate\View\Factory->renderComponent() at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\de8cc8a540bd2bbd1a15ade379196b12430814fd.php:123
 require() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:107
 Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:108
 Illuminate\Filesystem\Filesystem->getRequire() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:58
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:169
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:172
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:173
 Knuckles\Scribe\Writing\Writer->generateMarkdownOutputForEachRoute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:394
 Knuckles\Scribe\Writing\Writer->writeEndpointsMarkdownFile() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:136
 Knuckles\Scribe\Writing\Writer->writeMarkdownAndSourceFiles() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:104
 Knuckles\Scribe\Writing\Writer->writeDocs() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Commands\GenerateDocumentation.php:83
 Knuckles\Scribe\Commands\GenerateDocumentation->handle() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Container.php:596
 Illuminate\Container\Container->call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:136
 Illuminate\Console\Command->execute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Command\Command.php:258
 Symfony\Component\Console\Command\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:121
 Illuminate\Console\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:920
 Symfony\Component\Console\Application->doRunCommand() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:266
 Symfony\Component\Console\Application->doRun() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:142
 Symfony\Component\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Application.php:93
 Illuminate\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\laravel\lumen-framework\src\Console\Kernel.php:116
 Laravel\Lumen\Console\Kernel->handle() at F:\webapp\www\laravel\bigtaby\lumen\artisan:35

In 9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php line 8:

  [ErrorException]
  Undefined index: name (View: F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\resources\views\partials\body-parameters.blade.php)  


Exception trace:
  at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php:8
 Illuminate\View\Engines\CompilerEngine->handleViewException() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:60
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Concerns\ManagesComponents.php:96
 Illuminate\View\Factory->renderComponent() at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php:30
 require() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:107
 Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:108
 Illuminate\Filesystem\Filesystem->getRequire() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:58
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Concerns\ManagesComponents.php:96
 Illuminate\View\Factory->renderComponent() at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\de8cc8a540bd2bbd1a15ade379196b12430814fd.php:123
 require() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:107
 Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:108
 Illuminate\Filesystem\Filesystem->getRequire() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:58
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:169
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:172
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:173
 Knuckles\Scribe\Writing\Writer->generateMarkdownOutputForEachRoute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:394
 Knuckles\Scribe\Writing\Writer->writeEndpointsMarkdownFile() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:136
 Knuckles\Scribe\Writing\Writer->writeMarkdownAndSourceFiles() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:104
 Knuckles\Scribe\Writing\Writer->writeDocs() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Commands\GenerateDocumentation.php:83
 Knuckles\Scribe\Commands\GenerateDocumentation->handle() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Container.php:596
 Illuminate\Container\Container->call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:136
 Illuminate\Console\Command->execute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Command\Command.php:258
 Symfony\Component\Console\Command\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:121
 Illuminate\Console\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:920
 Symfony\Component\Console\Application->doRunCommand() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:266
 Symfony\Component\Console\Application->doRun() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:142
 Symfony\Component\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Application.php:93
 Illuminate\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\laravel\lumen-framework\src\Console\Kernel.php:116
 Laravel\Lumen\Console\Kernel->handle() at F:\webapp\www\laravel\bigtaby\lumen\artisan:35

In 9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php line 8:

  [ErrorException]       
  Undefined index: name  


Exception trace:
  at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php:8
 Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php:8
 require() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:107
 Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:108
 Illuminate\Filesystem\Filesystem->getRequire() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:58
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Concerns\ManagesComponents.php:96
 Illuminate\View\Factory->renderComponent() at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\9e2cb07d443d567cc13f353d218c97b7dd23a6f2.php:30
 require() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:107
 Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:108
 Illuminate\Filesystem\Filesystem->getRequire() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:58
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Concerns\ManagesComponents.php:96
 Illuminate\View\Factory->renderComponent() at F:\webapp\www\laravel\bigtaby\lumen\storage\framework\views\de8cc8a540bd2bbd1a15ade379196b12430814fd.php:123
 require() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:107
 Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\filesystem\Filesystem.php:108
 Illuminate\Filesystem\Filesystem->getRequire() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\PhpEngine.php:58
 Illuminate\View\Engines\PhpEngine->evaluatePath() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\Engines\CompilerEngine.php:61
 Illuminate\View\Engines\CompilerEngine->get() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:139
 Illuminate\View\View->getContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:122
 Illuminate\View\View->renderContents() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\view\View.php:91
 Illuminate\View\View->render() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:169
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:172
 Knuckles\Scribe\Writing\Writer->Knuckles\Scribe\Writing\{closure}() at n/a:n/a
 array_map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\collections\Collection.php:630
 Illuminate\Support\Collection->map() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:173
 Knuckles\Scribe\Writing\Writer->generateMarkdownOutputForEachRoute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:394
 Knuckles\Scribe\Writing\Writer->writeEndpointsMarkdownFile() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:136
 Knuckles\Scribe\Writing\Writer->writeMarkdownAndSourceFiles() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Writing\Writer.php:104
 Knuckles\Scribe\Writing\Writer->writeDocs() at F:\webapp\www\laravel\bigtaby\lumen\vendor\knuckleswtf\scribe\src\Commands\GenerateDocumentation.php:83
 Knuckles\Scribe\Commands\GenerateDocumentation->handle() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\container\Container.php:596
 Illuminate\Container\Container->call() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:136
 Illuminate\Console\Command->execute() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Command\Command.php:258
 Symfony\Component\Console\Command\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Command.php:121
 Illuminate\Console\Command->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:920
 Symfony\Component\Console\Application->doRunCommand() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:266
 Symfony\Component\Console\Application->doRun() at F:\webapp\www\laravel\bigtaby\lumen\vendor\symfony\console\Application.php:142
 Symfony\Component\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\illuminate\console\Application.php:93
 Illuminate\Console\Application->run() at F:\webapp\www\laravel\bigtaby\lumen\vendor\laravel\lumen-framework\src\Console\Kernel.php:116
 Laravel\Lumen\Console\Kernel->handle() at F:\webapp\www\laravel\bigtaby\lumen\artisan:35

**Comment by shalvah** [comment]
Did you follow the migration guide? Specifically the part about migrating to the new syntax for arrays and objects? See this person's issue - #124

**Comment by Talented-Business** [comment]
yes it is working
