### ISSUE TITLE
How to use multiple @apiResource scenarios for one endpoint?

### ISSUE THREAD

**Issue by jedlikowski** [knuckleswtf/scribe#544]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi guys,

I have a case of an endpoint which returns different data, different structure when called using an API key which belongs to either a User or an App. Depending on who calls the endpoint, completely different structure is returned. The check is done inside the api resource class which in turn calls other api resource classes to return the correct structure.

Now, what I want to achieve is to have 2 separate responses generated, showing both possible responses, with different scenarios. However scribe seems to ignore the second `@apiResource` and `@apiResourceModel` tags.

Example docblock I used:
```php
/**
* Show your data
*
* Get info about you (the owner of the API Key)
*
* @apiResource scenario="Calling as a user" App\Http\Resources\ExternalApi\ShowMeResponse
* @apiResourceModel App\User
* @apiResource scenario="Calling as an app" App\Http\Resources\ExternalApi\ShowMeResponse
* @apiResourceModel App\ApiApp
*
*/
```

![image](https://user-images.githubusercontent.com/9341608/199710940-61f99b42-5250-4311-8796-feb044c5f3f0.png)

**Comment by shalvah** [comment]
There are a few things going on:
1. I'm not certain, but I don't think the apiResource tag supports multiple scenarios yet. I know it's a gap I planned to fix, but I don't remember if I fixed it yet.
2. Even if it did, it's unlikely it would support different models, as it simply takes the first `apiResourceModel` tag it finds, and changing that logic would mean changing the parsing. In hindsight, we shouldn't have used a separate tag for this. Perhaps in the future, we'll support specifying the model directly on the `apiResource` tag, but I'm not yet decided.
3. If you're on PHP 8, though, you can use the attributes. They support this. And you can still keep your docblocks. https://scribe.knuckles.wtf/laravel/reference/annotations

**Comment by jedlikowski** [comment]
Thanks @shalvah , I tried to follow your guidance and change my tags into attributes but I still don't see multiple possible responses. They are there in the generated postman collection, but not in the generated OpenAPI spec. Since the spec uses response codes as keys in the map, only the last response is there. Can I somehow mitigate this to allow 2 different responses with the same status code? Or should I just give up? 😄

**Comment by shalvah** [comment]
Is that the only problem? AFAIK, the OpenAPI specification uses the response codes as keys, so not much we can change there...
